Adam
mimuw-anki/so pull request #1
Opened 2021-03-15 17:23 UTC by procrastinationfighter

First two lectures.

2021-03-16 22:40 UTC, jmolinski commented on so.txt
> +Sposobem podawania miejsca, skąd brane są elementy rozkazków.
literówka - rozkazków

2021-03-16 22:43 UTC, jmolinski requested changes

2021-03-16 22:43 UTC, jmolinski commented on so.txt
> +1
dodaj proszę nagłówek w formacie

```
deck_id: 737682189
deck_name: SO 
file_id: wyklad-1

```

na samym początku pliku

2021-03-16 22:43 UTC, jmolinski commented on so.txt
> +Sposobem podawania miejsca, skąd brane są elementy rozkazków.
literówka - rozkazków

2021-03-18 00:49 UTC, hcnt requested changes
jedna zmiana tylko i leci approve

2021-03-18 00:49 UTC, hcnt commented on so.txt
> +deck_name: SO
Zmień nazwę `SO` na `Systemy Operacyjne` lub `Systemy operacyjne`

2021-03-18 01:05 UTC, hcnt approved these changes
LGTM

2021-03-18 01:08 UTC, merged